services:
  - type: web
    name: exam-marks-sys
    env: python
    buildCommand: cd backend && pip install -r ../requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn wsgi:application --bind 0.0.0.0:$PORT
    runCommand: cd backend && python manage.py migrate && python create_superuser.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
